openapi: "3.0.0"
info:
  version: '1'
  title: Petstore, Limited
  description: asdf
  contact:
    name: Ed Vinyard <ed@stoplight.io>
  license:
    name: MIT
servers:
  - url: http://api.example.com/v1
tags:
  - name: pets
paths:
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      description: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: integer
                  name:
                    type: string
              examples:
                cat:
                  value:
                    id: 1
                    name: Fluffy
                dog:
                  value:
                    id: 2
                    name: Spot
                rock:
                  value:
                    id: 2
                    name: Pebbles
